### ISSUE TITLE
Linux equivalent to windows run.bat script

### ISSUE THREAD

**Issue by 06000208** [06000208/sandplate#4]
Would likely be a bash script

**Comment by Majinahanashi** [comment]
This would essentially merge into my recent enhancement issue posted.

**Comment by 06000208** [comment]
Yeah, issue #19

**Comment by 06000208** [comment]
Reopening this as a simple bash alternative to run.bat would be nice

**Comment by 06000208** [comment]
Closing this as #35 in 0.0.8+ would make this redundant.
